# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v5.3.2
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod:
  - hosts:
      - homegage.it
domains_test:
  - hosts:
      - test.homegage.it
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: it_IT
odoo_listdb: false
odoo_oci_image: ""
odoo_proxy: other
odoo_version: 16.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "15"
project_author: Daemo00
project_license: AGPL-3.0-or-later
project_name: Homegage
smtp_default_from: ""
smtp_relay_host: ""
